### ISSUE TITLE
openresty-opm 包缺失依赖

### ISSUE THREAD

**Issue by xiaooloong** [openresty/opm#37] opened 2016-11-23 08:52 UTC
`opm` 安装后使用时发生错误，提示 `Can't locate Digest/MD5.pm`

需要手动 `yum install perl-Digest-MD5`

**Comment by agentzh** [comment] 2016-11-25 19:37
@xiaooloong Thanks for the report. We'll look into this.

**Comment by agentzh** [comment] 2016-11-25 19:38
@xiaooloong BTW, this place is supposed to be English only. Thank you :)

**Comment by agentzh** [comment] 2016-11-25 22:26
Fixed in the git repository of openresty/openresty-package. Thanks!

**Closed by agentzh** 2016-11-25 22:26 UTC

**Comment by xiaooloong** [comment] 2016-12-06 08:19
@agentzh 
```
sh: resty: command not found
ERROR: luajit is required but is not available according to resty:
```
need to install `openresty-resty` manually

**Comment by agentzh** [comment] 2016-12-06 18:45
@xiaooloong Yes, it is expected and by design. The `openresty-resty` package depends on `openresty` but not the other way around. See

http://openresty.org/en/rpm-packages.html
