### ISSUE TITLE
Issues with downloading packages when behind a proxy

### ISSUE THREAD

**Issue by zonak** [openresty/opm#42] opened 2016-12-14 12:55 UTC
Tried the package manager via regular connection and it worked as expected.

When I attempt to run in it on a VM that is behind a proxy, I am getting the following error:

```
ERROR: unexpected server response status code for URL "https://opm.openresty.org/api/pkg/fetch?account=pintsized&name=lua-resty-redis-connector&op=&version=": 200
```

I did some research and most likely the issue is caused by the fact that when trying to get the HTTP status code via _curl_, _opm_ expects to see _302_ but the proxy responds with something like this:

```
HTTP/1.1 200 Connection established
Content-Length: 0

HTTP/1.1 302 Moved Temporarily
Cache-Control: max-age=180
Content-Type: text/html
Date: Tue, 13 Dec 2016 20:56:03 GMT
Expires: Tue, 13 Dec 2016 20:59:03 GMT
Location: /api/pkg/tarball/pintsized/lua-resty-redis-connector-0.03.opm.tar.gz
Server: openresty
X-File-Checksum: 2b9dfc20-56fe-1885-322b-5fd016aa7057
Content-Length: 154
Connection: keep-alive
```

which means it sends two status codes (_200_ for the proxy connection and _302_ from the server) and the regular expression is getting _200_ instead of _302_ which is why we are probably getting the mentioned error.

We can probably get around it by formatting the _curl_ response with something like this:

```
 my $cmd = qq/curl -s -w "%{http_code}" -i -A '$UserAgent' '$url'/;
```

but still couldn't get it to work all the way.

Hope there is an easy workaround for this.

**Comment by zonak** [comment] 2016-12-14 13:57
After going over the code in a little bit more detail what I previously suggested will not work.

I tried adding the following logic:

```perl
while (<$in>) {
    if ($_ =~ m{^ HTTP/\d+\.\d+ \s+ (\d+) \b }x) {
        $status_line = $_;
        if ($1 eq '302') {
            last;
        }
    }
}
```

which effectively moves the iteration to the right spot in the _curl_ response. This worked for me, but no _perl_ expert and no deep knowledge of the whole code base but I thought it might give you something useful to start with.

**Comment by agentzh** [comment] 2016-12-14 19:55
@zonak How exactly did you configure your proxy? It would be much easier to fix if we can reproduce the problem on our side :)

**Comment by zonak** [comment] 2016-12-14 20:31
I apply the recommended method of using a proxy with _curl_ (and many other _cli_ tools) by setting the `HTTP_PROXY` and / `HTTPS_PROXY` env variables.

Please let me know if I can provide any further clarifications on this.

**Comment by agentzh** [comment] 2016-12-15 01:50
@zonak Will you please try out the following patch for the `opm` script on your side?

```diff
diff --git a/bin/opm b/bin/opm
index 195d56a..bad1d9f 100755
--- a/bin/opm
+++ b/bin/opm
@@ -73,6 +73,7 @@ sub test_version_spec ($$$$$);
 sub check_utf8_field ($$$);
 sub check_user_file_path ($$$$);
 sub rebase_path ($$$);
+sub trim_curl_out ($);
 
 GetOptions("h|help",          \(my $help),
            "cwd",             \(my $install_into_cwd),
@@ -1189,6 +1190,8 @@ sub install_target ($$) {
 
     my $cmd = qq/curl -sS -i -A '$UserAgent' '$url'/;
     my $out = `$cmd`;
+    $out = trim_curl_out $out;
+
     if ($? != 0) {
         err "failed to run command \"$cmd\"\n";
     }
@@ -1300,15 +1303,23 @@ sub install_target ($$) {
     open $in, $header_file or
         err "failed to open $header_file for reading: $!\n";
 
-    $status_line = <$in>;
-    if ($status_line !~ m{^ HTTP/\d+\.\d+ \s+ (\d+) \b }x) {
+    undef $status_line;
+    {
+        my $out = do { local $/; <$in> };
+        close $in or err "failed to close file $header_file: $!";
+
+        $out = trim_curl_out $out;
+        if ($out =~ /\A([^\n]*)/) {
+            $status_line = $1;
+        }
+    }
+
+    if (!defined $status_line || $status_line !~ m{^ HTTP/\d+\.\d+ \s+ (\d+) \b }x) {
         err "bad response status line received from server for URL \"$url\".\n";
     }
 
     $status = $1;
 
-    close $in or err "failed to close file $header_file: $!";
-
     #warn $status;
     if ($status ne '200') {
         err "failed to fetch $dist_file: server returns bad status code $status.\n";
@@ -2095,6 +2106,8 @@ sub do_search {
 
     my $url = "$download_url/api/pkg/search?q=$escaped_query";
     my $out = `curl -i -sS '$url' 2>&1`;
+    $out = trim_curl_out $out;
+
     my $status;
     if ($? == 0 && $out =~ m{^ HTTP/1\.\d \s+ (\d+) \b}ix) {
         $status = $1;
@@ -2122,6 +2135,8 @@ sub search_pkg_name ($$) {
 
     my $url = "$download_url/api/pkg/search/name?q=$name";
     my $out = `curl -i -sS '$url' 2>&1`;
+    $out = trim_curl_out $out;
+
     my $status;
     if ($? == 0 && $out =~ m{^ HTTP/1\.\d \s+ (\d+) \b}ix) {
         $status = $1;
@@ -2283,6 +2298,16 @@ sub is_valid_dist_name ($$) {
     }
 }
 
+sub trim_curl_out ($) {
+    my $s = shift;
+
+    if (defined $s) {
+        $s =~ s{\AHTTP/1\.1 200 Connection established\r\n.*?\r\n\r\n}{}ms;
+    }
+
+    $s;
+}
+
 sub usage {
     my $rc = shift;
 
```

Please try as many opm commands as possible with the http proxy enabled on your side. Many thanks!

**Comment by zonak** [comment] 2016-12-15 12:50
@agentzh thank you for the prompt response.
Applied the patch and tested all the commands - everything seems to be working great now.

**Comment by agentzh** [comment] 2016-12-15 19:11
@zonak Thanks for your feedback!

@doujiang24 @membphis @moonbingbing Will you please review my patch above? If it is okay, I'll commit it :) Thanks!

**Comment by doujiang24** [comment] 2016-12-16 06:07
@agentzh LGTM:)

**Comment by moonbingbing** [comment] 2016-12-16 06:23
Looks good to me

**Comment by detailyang** [comment] 2016-12-16 06:27
by the way `my $out = do { local $/; <$in> };` is [Perl Idioms](http://www.perlmonks.org/?node_id=287647) which i took minutes to googling it :)

**Comment by agentzh** [comment] 2016-12-16 20:40
@detailyang Aye.

**Comment by agentzh** [comment] 2016-12-16 20:51
Patch committed. Thank you all!

**Closed by agentzh** 2016-12-16 20:51 UTC

**Comment by thibaultcha** [comment] 2016-12-20 07:01
@agentzh Sorry for passing on this; I am not yet familiar with opm especially since I haven't started using it for my libraries yet :) (adding it to my 2017 resolutions)
